### PR TITLE
Add raw_text property to DialogueResource

### PR DESCRIPTION
**Pull request by feendrache**
- the raw_text variable was added to the dialogue resource
- parser, parser_result and import_plugin were changed to import the new var

### CODE REVIEW

**Comment by nathanhoad** [comment]
Would you be able to add a use case for the raw text? I'm not sure it would be needed in a running game.

**Comment by feendrache** [comment]
My NPCs have a dialogue variable wich is an array and stores the current available dialogues of the npc.
When the player wants to talk to the npcs and there are more than one dialogue i need to create a selector dialogue where the player can choose wich dialogue to follow.
Since this dialogue is constructed via script i need to import the following dialogues. The standard import and selectors won't work during runtime, tested it

**Comment by feendrache** [comment]
So to add some code reference:
I construct the selector dialogue in script and the use `DialogueManager.create_resource_from_text(sub_dialogue)`
When i use the dialogue manger import and reference stuff it works in editor run but in build is gives an error that it wasn't able t find the files it's supposed to import. 

I created a function that reads the dialogue raw text and constructs a dialogue where all the referenced dialogues are put into one dialogue in different sections. The dialogue-files all have a "selector" and a "dialogue" section. The selector section builds the selector dialogue and the dialogue section the jump to part after the selection. 
I use the raw_text version since there may be variables named the same in the sub dialogues and i need to replace names and rework stuff to work correctly.

**Comment by nathanhoad** [comment]
I'm still not really sure what you're trying to do but this change seems harmless enough so I'll merge it 👍

**Pull request merged**
